import './globals.css';

import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { Toaster } from 'sonner';

import { GoogleAnalytics } from '@/components/google-analytics';
import { Providers } from '@/components/layout/providers';
import { TopLoader } from '@/components/layout/top-loader';

import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html suppressHydrationWarning lang="en">
			<body>
				<TopLoader />
				<NuqsAdapter>
					<Providers>
						<Toaster />
						{children}
					</Providers>
				</NuqsAdapter>
			</body>
			<GoogleAnalytics />
		</html>
	);
}
